# -*- coding: utf-8 -*-
"""techsesh.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g9ZacO1Y1Zrfif_e9pFOfq7fPhgIPE1u
"""

# Keywords are presented in purple
import

letters = ['a','b','c']
del letters[0]
print(letters)

t = ['a','b','c','d','e','f']
t[1:3]

t[:4]

t[3:]

t[:] #print whole list

t[::-1] #reversing a list

# create a tuple and give one ele and the two or more eles
t = (1,)
print(t)
type(t)

A = ('a','b','c','d')
print(A)
type(A)

dict = {'name':'Yoshitha',
        'age':19,
        'class':'III-I',
        'fruits': ['Mango','Apple']
        }
print(dict)

dict = {1: 'Geeks', 2: 'for', 3: 'Geeks'}
print(dict)

